[package]
name = "emp_tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.9" }
structopt = { version = "0.3" }
rand_core = { version = "0.9" }
bytemuck = {version = "1.24", features = ["derive"]}
rayon = {version = "1.11"}

[target."cfg(target_arch = \"aarch64\")".dependencies]
sha2 = { version = "0.10.9", features = ["asm"] }
[target."cfg(any(target_arch = \"x86\", target_arch = \"x86_64\"))".dependencies]
sha2 = {version = "0.10.9"}

[dev-dependencies]
rand = { version = "0.9" }
rand_chacha = { version = "0.9" }
criterion = { version = "0.7" }

[[bench]]
name = "block"
harness = false

[[bench]]
name = "aes"
harness = false

[[bench]]
name = "hash"
harness = false

[[bench]]
name = "prg"
harness = false

[[bench]]
name = "ggm"
harness = false

[[bench]]
name = "lpn"
harness = false

[[example]]
name = "netio"
path = "examples/netio.rs"

[[example]]
name = "prg"
path = "examples/prg.rs"
